# Generated by Django 5.0.7 on 2024-07-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropRecommendation',
            fields=[
                ('cropId', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('N', models.PositiveIntegerField()),
                ('P', models.PositiveIntegerField()),
                ('K', models.PositiveIntegerField()),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('ph', models.FloatField(blank=True, null=True)),
                ('rainfall', models.FloatField(blank=True, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('prediction', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PreviousCropRequest',
            fields=[
                ('requestId', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('season', models.CharField(max_length=20)),
                ('month', models.PositiveIntegerField()),
                ('crop', models.CharField(max_length=100)),
                ('area', models.FloatField()),
                ('production', models.FloatField(blank=True, null=True)),
                ('yield_per_hectare', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
