# Generated by Django 5.0.7 on 2024-07-26 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CRS', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='croprecommendation',
            name='landId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.landmark'),
        ),
        migrations.AddField(
            model_name='croprecommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='previouscroprequest',
            name='landId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.landmark'),
        ),
        migrations.AddField(
            model_name='previouscroprequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
